### ISSUE TITLE
app.model(modelName, settings) was removed

### ISSUE THREAD

**Issue by bheru27** [mrbatista/loopback-component-paypal#1]
After installing this in a new loopback instance and running it, it gives the following error:

Error: app.model(modelName, settings) is no longer supported. Use app.registry.createModel(modelName, definition) and app.model(ModelCtor, config) instead.

Checking the release notes it says:
https://loopback.io/doc/en/lb3/3.0-Release-Notes.html#appmodelmodelname-settings-was-removed

Just a matter of updating this to match the criteria. i could work on it (its trivial) but i dont have much time today

**Comment by mrbatista** [comment]
@bheru27 I have refactoring library from component to connector to allow multiple paypal account.
PR #3 resolve your issue.
